spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sibanarayan014@gmail.com
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: hii-coders
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${GOOGLE_AUTH_CLIENT_ID}
            client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
            scope:
              - email
              - profile

          github:
            client-id: ${GITHUB_AUTH_CLIENT_ID}
            client-secret: ${GITHUB_AUTH_CLIENT_SECRET}
            scope:
              - user:email

  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: postgres
    password: mshiv001
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    repair-on-migrate: true
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: submission-result
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 10
      fetch-min-size: 1
      fetch-max-wait: 500ms
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.sibanarayan.code.events"
      listener:
        ack-mode: RECORD

  cors:
    allowed-origins: "http://localhost:5173"
server:
  port: 8083

